[versions]
kotlin = "2.1.0"
fabric-loom = "1.9-SNAPSHOT"
minecraft = "1.21.4"
yarn = "1.21.4+build.8"
loader = "0.16.10"
kotlin-loader = "1.13.1+kotlin.2.1.10"
fabric-api = "0.115.1+1.21.4"
modmenu = "13.0.1"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "loader" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "kotlin-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
